image: verdigrix/splat:python3.5-dev

stages:
  - build
  - test

build:
  stage: build
  artifacts:
    paths:
      - build/lib*
      - build/scripts*
      - _splat.so
  script:
    - python3 setup.py build
    - ln -s $(find build -name "_splat.cpython*.so") _splat.so

build_fast:
  stage: build
  artifacts:
    paths:
      - build-fast/lib*
      - build-fast/scripts*
      - _splat.so.fast
  script:
    - CFLAGS="$CFLAGS -DSPLAT_FAST -msse2 -O3" python3 setup.py build --build-base=build-fast
    - ln -s $(find build-fast -name "_splat.cpython*.so") _splat.so.fast

test:
  stage: test
  dependencies: [build]
  script:
    - python3 test.py

test_fast:
  stage: test
  dependencies: [build, build_fast]
  script:
    - python3 fast_test.py
    - mv _splat.so _splat.so.std; ln -s _splat.so.fast _splat.so
    - python3 fast_test.py --compare
